# Generated by Django 4.1.4 on 2023-01-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='角色名称', max_length=64, verbose_name='角色名称')),
                ('code', models.CharField(help_text='角色编码', max_length=64, unique=True, verbose_name='角色编码')),
                ('status', models.BooleanField(default=True, help_text='角色状态', verbose_name='角色状态')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
                'db_table': 'system_role',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(help_text='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('username', models.CharField(db_index=True, help_text='用户名', max_length=150, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, help_text='邮箱', max_length=255, null=True, verbose_name='邮箱')),
                ('mobile', models.CharField(blank=True, help_text='联系方式', max_length=255, null=True, verbose_name='联系方式')),
                ('status', models.BooleanField(default=True, help_text='状态', verbose_name='状态')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')], default=1, help_text='性别', verbose_name='性别')),
                ('role', models.ManyToManyField(db_constraint=False, help_text='关联角色', to='system.role', verbose_name='关联角色')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'system_users',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
