# Generated by Django 4.1.4 on 2023-01-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(help_text='编号', primary_key=True, serialize=False, verbose_name='编号')),
                ('create_time', models.DateTimeField(auto_now=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='资产名称', max_length=125, verbose_name='资产名称')),
                ('kind', models.CharField(help_text='资产种类', max_length=125, verbose_name='资产种类')),
                ('location', models.CharField(help_text='资产所在地', max_length=125, verbose_name='资产所在地')),
                ('owner', models.CharField(help_text='资产所属人', max_length=125, verbose_name='资产所属人')),
                ('scrap_time', models.DateTimeField(blank=True, help_text='报废时间', null=True, verbose_name='报废时间')),
            ],
        ),
    ]
